version: "3.8"
services:
  webflux:
    container_name: webflux
    image: webflux:0.0.1-SNAPSHOT
    ports: # host:container
      - "8080:8080"
    environment:
      - spring.profiles.active=stress
      - spring.r2dbc.url=r2dbc:pool:mariadb://192.168.0.71:3306/sample
      - logging.level.org.springframework.r2dbc.core=off