### TxId
GET {{domain}}/test/txid
Content-Type: application/json
#x-txid: test

### TxId error
POST {{domain}}/test/txid2
Content-Type: application/json
#x-txid: test

### error
PUT {{domain}}/test/error?qq=11
Content-Type: application/json

{
  "id": "123",
  "age": 11,
  "birthday": "2024.02.29",
  "message": "err1"
}

### circuit breaker (success)
GET {{domain}}/test/circuit-breaker
Content-Type: application/json

### circuit breaker (fail)
GET {{domain}}/test/circuit-breaker?flag=false
Content-Type: application/json

### rate limiter
GET {{domain}}/test/rate-limiter
Content-Type: application/json

### actuator
GET {{domain}}/actuator/health
Content-Type: application/json