version: "3.8"
services:
  mvc:
    container_name: mvc
    image: spring-mvc:0.0.1-SNAPSHOT
    ports: # host:container
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mariadb://10.202.96.73:3306/sample
      - api.external=http://10.202.96.73:8091