spring:
  application:
    name: webflux.coroutine
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/sample
    username: user
    password: 1234
  sql:
    init:
      mode: always
      schema-locations: classpath:script-db/schema.sql
server:
  shutdown: graceful
  compression:
    enabled: true
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
logging:
  level:
    dev.fastcampus.webflux: debug
