spring:
  application:
    name: useless-webflux
  output:
    ansi:
      enabled: always
server:
  port: 8091
  error:
    include-exception: true
    include-message: always
    include-stacktrace: never
logging:
  level:
    dev.fastcampus: debug